/**
 * lively-mascot · Emotion Definitions
 *
 * Grouped by:
 * - Lifecycle (00-09): Core states like idle, sleeping, waking up.
 * - Reactions (10-19): Immediate responses to user actions.
 * - Work States (20-31): What the bot/agent is doing (thinking, searching, etc.).
 *
 * Each emotion can define:
 * - bodyAnim:   CSS animation override for .lively-body
 * - bodyFilter: CSS filter override for .lively-body
 * - blink:      false = force eyes closed/locked (default true)
 * - gaze:       false = pause cursor tracking (default true)
 * - hop:        true = allow interval-driven hopping for this expression
 * - leafAnim:   CSS animation override for .lively__leaf
 * - footAnim:   CSS animation override for .lively__foot
 */

var LivelyEmotions = {
  // ===================== LIFECYCLE (00-09) =====================
  "00": { id: "00", name: "Sleep",      group: "lifecycle", desc: "深度睡眠",
          blink: false, gaze: false,
          bodyFilter: "brightness(0.55) saturate(0.6)",
          leafAnim: "lively-leaf-sleep 6s ease-in-out infinite",
          footAnim: "lively-foot-rest 4s ease-in-out infinite" },
  "01": { id: "01", name: "Wake",       group: "lifecycle", desc: "刚睡醒",
          bodyAnim: "lively-wake 1.2s ease-out",
          leafAnim: "lively-leaf-wake 0.8s ease-out",
          footAnim: "lively-foot-wake 0.6s ease-out" },
  "02": { id: "02", name: "Idle",       group: "lifecycle", desc: "待机" },
  "03": { id: "03", name: "Breathe",    group: "lifecycle", desc: "平稳呼吸",
          bodyAnim: "lively-deep-breathe 4s ease-in-out infinite",
          leafAnim: "lively-leaf-breathe 4s ease-in-out infinite",
          footAnim: "lively-foot-rest 4s ease-in-out infinite" },
  "04": { id: "04", name: "Ready",      group: "lifecycle", desc: "随时待命",
          bodyAnim: "lively-ready 2s ease-in-out infinite",
          leafAnim: "lively-leaf-ready 1.5s ease-in-out infinite",
          footAnim: "lively-foot-ready 1.8s ease-in-out infinite" },
  "05": { id: "05", name: "Pause",      group: "lifecycle", desc: "暂停中",
          bodyFilter: "saturate(0.4) brightness(0.85)",
          leafAnim: "lively-leaf-pause 6s ease-in-out infinite",
          footAnim: "lively-foot-rest 4s ease-in-out infinite" },
  "06": { id: "06", name: "Refresh",    group: "lifecycle", desc: "正在刷新",
          bodyAnim: "lively-refresh 0.8s ease-in-out infinite",
          leafAnim: "lively-leaf-refresh 0.6s ease-in-out infinite" },
  "07": { id: "07", name: "LowBattery", group: "lifecycle", desc: "电量不足",
          bodyFilter: "saturate(0.3) brightness(0.7)",
          bodyAnim: "lively-lowbatt 2.5s ease-in-out infinite",
          leafAnim: "lively-leaf-droop 3s ease-in-out infinite",
          footAnim: "lively-foot-rest 5s ease-in-out infinite" },
  "08": { id: "08", name: "Offline",    group: "lifecycle", desc: "已离线",
          blink: false, gaze: false,
          bodyFilter: "grayscale(1) brightness(0.5)",
          leafAnim: "lively-leaf-droop 8s ease-in-out infinite" },
  "09": { id: "09", name: "Boot",       group: "lifecycle", desc: "启动中",
          bodyAnim: "lively-boot 0.5s ease-in-out 3",
          leafAnim: "lively-leaf-boot 0.4s ease-out 3",
          footAnim: "lively-foot-boot 0.3s ease-out 3" },

  // ===================== REACTIONS (10-19) =====================
  "10": { id: "10", name: "Happy",     group: "reaction", desc: "开心",
          gaze: false,
          bodyAnim: "lively-happy-bounce 0.6s ease-in-out 2",
          leafAnim: "lively-leaf-happy 0.4s ease-in-out 4",
          footAnim: "lively-foot-happy 0.35s ease-in-out 4" },
  "11": { id: "11", name: "Excited",   group: "reaction", desc: "兴奋",
          gaze: false,
          bodyAnim: "lively-excited 0.5s ease-in-out 3",
          leafAnim: "lively-leaf-excited 0.3s ease-in-out 5",
          footAnim: "lively-foot-excited 0.25s ease-in-out 6" },
  "12": { id: "12", name: "Sad",       group: "reaction", desc: "难过",
          gaze: false,
          bodyAnim: "lively-sad 3s ease-in-out infinite",
          bodyFilter: "brightness(0.85) saturate(0.7)",
          leafAnim: "lively-leaf-droop 2s ease-in-out infinite",
          footAnim: "lively-foot-rest 4s ease-in-out infinite" },
  "13": { id: "13", name: "Angry",     group: "reaction", desc: "生气",
          gaze: false,
          bodyAnim: "lively-angry 0.15s linear infinite",
          bodyFilter: "hue-rotate(340deg) saturate(1.5) brightness(0.95)",
          leafAnim: "lively-leaf-angry 0.12s linear infinite",
          footAnim: "lively-foot-stomp 0.18s ease-in-out infinite" },
  "14": { id: "14", name: "Surprised", group: "reaction", desc: "惊讶",
          gaze: false,
          bodyAnim: "lively-surprise 0.5s ease-out",
          leafAnim: "lively-leaf-wake 0.5s ease-out" },
  "15": { id: "15", name: "Shy",       group: "reaction", desc: "害羞",
          gaze: false,
          bodyAnim: "lively-confused 2s ease-in-out infinite",
          leafAnim: "lively-leaf-shy 2s ease-in-out infinite" },
  "16": { id: "16", name: "Love",      group: "reaction", desc: "心动",
          gaze: false,
          bodyAnim: "lively-love-pulse 0.8s ease-in-out infinite",
          leafAnim: "lively-leaf-happy 0.6s ease-in-out infinite" },
  "17": { id: "17", name: "Confused",  group: "reaction", desc: "困惑",
          bodyAnim: "lively-confused 2s ease-in-out infinite",
          leafAnim: "lively-leaf-confused 1.5s ease-in-out infinite" },
  "18": { id: "18", name: "Cool",      group: "reaction", desc: "耍酷",
          bodyFilter: "contrast(1.15) brightness(1.05)",
          leafAnim: "lively-leaf-ready 2s ease-in-out infinite" },
  "19": { id: "19", name: "Smug",      group: "reaction", desc: "得意",
          bodyAnim: "lively-smug 2s ease-in-out infinite",
          leafAnim: "lively-leaf-ready 1.8s ease-in-out infinite" },

  // ===================== WORK STATES (20-31) =====================
  "20": { id: "20", name: "Thinking",   group: "work", desc: "思考中",
          blink: false,
          bodyAnim: "lively-thinking 2.5s ease-in-out infinite",
          leafAnim: "lively-leaf-thinking 2s ease-in-out infinite" },
  "21": { id: "21", name: "Listening",  group: "work", desc: "倾听中",
          bodyAnim: "lively-listening 2s ease-in-out infinite",
          leafAnim: "lively-leaf-listen 1.8s ease-in-out infinite" },
  "22": { id: "22", name: "Talking",    group: "work", desc: "说话中",
          bodyAnim: "lively-talking 0.5s ease-in-out infinite",
          leafAnim: "lively-leaf-talking 0.8s ease-in-out infinite" },
  "23": { id: "23", name: "Searching",  group: "work", desc: "搜索中",
          bodyAnim: "lively-searching 1.5s ease-in-out infinite",
          leafAnim: "lively-leaf-searching 1.2s ease-in-out infinite",
          footAnim: "lively-foot-pace 0.8s ease-in-out infinite" },
  "24": { id: "24", name: "Reading",    group: "work", desc: "阅读中",
          bodyAnim: "lively-reading 3s ease-in-out infinite",
          leafAnim: "lively-leaf-reading 2.5s ease-in-out infinite" },
  "25": { id: "25", name: "Writing",    group: "work", desc: "写作中",
          bodyAnim: "lively-writing 1.8s ease-in-out infinite",
          leafAnim: "lively-leaf-writing 1.5s ease-in-out infinite",
          footAnim: "lively-foot-writing 1.2s ease-in-out infinite" },
  "26": { id: "26", name: "Coding",     group: "work", desc: "编程中",
          blink: false,
          bodyAnim: "lively-coding 2.5s ease-in-out infinite",
          leafAnim: "lively-leaf-coding 2s ease-in-out infinite" },
  "27": { id: "27", name: "Designing",  group: "work", desc: "设计中",
          bodyAnim: "lively-designing 3s ease-in-out infinite",
          leafAnim: "lively-leaf-designing 2.5s ease-in-out infinite" },
  "28": { id: "28", name: "Loading",    group: "work", desc: "加载中",
          gaze: false,
          // Loading state is communicated by the rotated ring (CSS).
          // Disable the base body sway so the ring stays concentric; the
          // whole rig bounces instead to make the live mascot feel alive.
          bodyAnim: "lively-loading-bounce 0.9s ease-in-out infinite",
          footAnim: "lively-foot-rest 3s ease-in-out infinite" },
  "29": { id: "29", name: "Processing", group: "work", desc: "处理中",
          bodyAnim: "lively-processing 1.5s ease-in-out infinite",
          leafAnim: "lively-leaf-thinking 1.2s ease-in-out infinite" },
  "30": { id: "30", name: "Success",    group: "work", desc: "任务完成",
          gaze: false,
          bodyAnim: "lively-success 0.7s ease-out",
          leafAnim: "lively-leaf-happy 0.5s ease-out 2" },
  "31": { id: "31", name: "Error",      group: "work", desc: "发生错误",
          gaze: false,
          bodyFilter: "brightness(0.8) saturate(0.6)",
          bodyAnim: "lively-error 0.25s linear 4",
          leafAnim: "lively-leaf-error 0.2s linear 4" },

  // ===================== EXTENDED (32-34) =====================
  "32": { id: "32", name: "Grateful",   group: "reaction", desc: "感谢",
          gaze: false,
          bodyAnim: "lively-love-pulse 1.2s ease-in-out infinite",
          leafAnim: "lively-leaf-happy 1s ease-in-out infinite" },
  "33": { id: "33", name: "Retrying",   group: "work", desc: "重试中",
          bodyAnim: "lively-searching 1.2s ease-in-out infinite",
          leafAnim: "lively-leaf-confused 1s ease-in-out infinite",
          footAnim: "lively-foot-pace 0.6s ease-in-out infinite" },
  "34": { id: "34", name: "Cancelled",  group: "work", desc: "已取消",
          bodyFilter: "saturate(0.5) brightness(0.8)",
          leafAnim: "lively-leaf-droop 3s ease-in-out infinite",
          footAnim: "lively-foot-rest 3s ease-in-out infinite" },
  "35": { id: "35", name: "Crying",     group: "reaction", desc: "哭泣",
          gaze: false,
          bodyFilter: "brightness(0.9) saturate(0.8)",
          bodyAnim: "lively-sad 2s ease-in-out infinite",
          leafAnim: "lively-leaf-droop 1.5s ease-in-out infinite",
          footAnim: "lively-foot-rest 3s ease-in-out infinite" },
  "36": { id: "36", name: "Bored",      group: "reaction", desc: "无聊",
          bodyAnim: "lively-bored 4s ease-in-out infinite",
          leafAnim: "lively-leaf-droop 5s ease-in-out infinite",
          footAnim: "lively-foot-rest 4s ease-in-out infinite" },
  "37": { id: "37", name: "Nervous",    group: "reaction", desc: "紧张",
          bodyAnim: "lively-nervous 0.8s ease-in-out infinite",
          leafAnim: "lively-leaf-nervous 0.6s ease-in-out infinite",
          footAnim: "lively-foot-nervous 0.3s ease-in-out infinite" },
  "38": { id: "38", name: "Eureka",     group: "reaction", desc: "灵光一现",
          gaze: false,
          bodyAnim: "lively-eureka 0.6s ease-out",
          leafAnim: "lively-leaf-eureka 0.4s ease-out 2",
          footAnim: "lively-foot-happy 0.3s ease-out 3" },
  "39": { id: "39", name: "Waiting",    group: "work", desc: "等待中",
          bodyAnim: "lively-waiting 2s ease-in-out infinite",
          leafAnim: "lively-leaf-waiting 1.5s ease-in-out infinite",
          footAnim: "lively-foot-tap 0.5s ease-in-out infinite" }
};

var LivelyEmotionGroups = {
  "lifecycle": { name: "生命周期", order: 0 },
  "reaction":  { name: "情绪反应", order: 1 },
  "work":      { name: "工作状态", order: 2 }
};
